e_rick:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # # Position Controllers ---------------------------------------
  right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: Rear_wheel_1_joint 
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: Rear_wheel_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  fork_position_controller:
    type:  effort_controllers/JointPositionController
    joint: Fork_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
